# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-07 01:07
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0002_counties'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlueEarth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areasymbol', models.CharField(max_length=20)),
                ('spatialver', models.BigIntegerField()),
                ('musym', models.CharField(max_length=6)),
                ('mukey', models.CharField(max_length=30)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.AlterModelOptions(
            name='counties',
            options={'verbose_name_plural': 'Counties'},
        ),
        migrations.AlterModelOptions(
            name='incidences',
            options={'verbose_name_plural': ' Incidences'},
        ),
        migrations.AlterModelManagers(
            name='incidences',
            managers=[
            ],
        ),
    ]
